/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as NewRouteImport } from './routes/new'
import { Route as MoreRouteImport } from './routes/more'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntryIdRouteImport } from './routes/entry.$id'

const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryIdRoute = EntryIdRouteImport.update({
  id: '/entry/$id',
  path: '/entry/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/more': typeof MoreRoute
  '/new': typeof NewRoute
  '/statistics': typeof StatisticsRoute
  '/entry/$id': typeof EntryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/more': typeof MoreRoute
  '/new': typeof NewRoute
  '/statistics': typeof StatisticsRoute
  '/entry/$id': typeof EntryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/more': typeof MoreRoute
  '/new': typeof NewRoute
  '/statistics': typeof StatisticsRoute
  '/entry/$id': typeof EntryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calendar' | '/more' | '/new' | '/statistics' | '/entry/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calendar' | '/more' | '/new' | '/statistics' | '/entry/$id'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/more'
    | '/new'
    | '/statistics'
    | '/entry/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  MoreRoute: typeof MoreRoute
  NewRoute: typeof NewRoute
  StatisticsRoute: typeof StatisticsRoute
  EntryIdRoute: typeof EntryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/$id': {
      id: '/entry/$id'
      path: '/entry/$id'
      fullPath: '/entry/$id'
      preLoaderRoute: typeof EntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  MoreRoute: MoreRoute,
  NewRoute: NewRoute,
  StatisticsRoute: StatisticsRoute,
  EntryIdRoute: EntryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
